openapi: 3.0.3
tags:
  - "Content of a document"
summary: "To get the content of an uploaded PDF document"
description: "This route allows to get the content of an uploaded PDF document. Replace the {id} parameter by the target ID of the document. This ID was returned in response of an upload file request"
get:
  description: "None"
parameters:
  - name: doc_id
    in: path
    description: "Identifier of the document"
    type: integer
    required: true
    minimum: 0
    maximum: 1000000
    format: int32
responses:
    '200':
          description: "Successful response"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Content"
    '400':
          description: "Bad Request"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Message"
    '500':
          description: "Internal Server Error"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Message"
