openapi: 3.0.3
tags:
  - name: Metadata and Named Entities of a document 
get:
  description: None
parameters:
  - name: doc_id
    in: doc_id
    description: Identifier of the document
    type: integer
    required: true
    default: 1
responses:
    '200':
          description: Successful response
    '400':
          description: Bad Request
    '500':
          description: Internal Server Error
