openapi: 3.0.3
tags:
  - name: Metadata and Named Entities of a document 
get:
  description: None
responses:
    '200':
          description: Successful response
    '400':
          description: Bad Request
    '500':
          description: Internal Server Error
