openapi: 3.0.3
tags:
  - name: Upload a PDF document
summary: "To upload a PDF document"
description: "To upload a PDF document"
produces:
- "application/json"
post:
  description: To upload a PDF document
responses:
    '200':
          description: Successful response
    '400':
          description: Bad Request
    '500':
          description: Internal Server Error
