openapi: 3.0.3
tags:
  - "Upload a PDF document"
summary: "To upload a PDF document"
description: "This route allows to upload a PDF document"
produces:
- "application/json"
post:
  description: "To upload a PDF document"
responses:
    '200':
          description: "Successful response"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Message"
    '400':
          description: "Bad Request"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Message"
    '500':
          description: "Internal Server Error"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Message"
