name: Pylint

on:
  push:
    branches: '*'

  workflow_dispatch:

jobs:
  analysis:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        sudo apt-get install build-essential libpoppler-cpp-dev pkg-config python3-dev
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        export PYTHONPATH="venv/lib/python3.9/site-packages/"
        pylint --disable too-many-return-statements \
        --disable too-many-instance-attributes \
        --disable too-few-public-methods \
        --disable too-many-locals \
        --disable too-many-arguments \
        --disable c-extension-no-member \
        web_service/*
